version: '3'

services:
  cassandra:
    build:
      context: ./test/docker
      dockerfile: cassandra.dockerfile
    ports:
      - "9043:9042"
    environment:
      - HEAP_NEWSIZE=1M
      - MAX_HEAP_SIZE=200M
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 20s
      timeout: 10s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: 50m
