name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      cassandra:
        image: cassandra
        ports:
        - 9043:9042
        options: --health-cmd "cqlsh --debug" --health-interval 5s --health-retries 10

    env:
      MIX_ENV: test
      CASSANDRA_PORT: 9043

    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: 1.12.3
              otp: 24.0.6
            lint: lint

    steps:
      - uses: actions/checkout@v2

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.pair.otp }}
          elixir-version: ${{ matrix.pair.elixir }}

      - name: Dependencies
        run: mix deps.get

      - name: Check Format
        run: mix format --check-formatted
        if: ${{ matrix.lint }}

      - name: Check Unused Dependencies
        run: mix deps.unlock --check-unused
        if: ${{ matrix.lint }}

      - name: Run Tests
        run: mix test
